name: CI

on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: '6.0.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v3.1.1

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: 3.13

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      # Update output format to enable automatic inline annotations.
      - name: Run Ruff check
        run: ruff check --output-format=github .

      - name: Run Ruff format
        run: ruff format --output-format=github .
